version: 1.0.{build}
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|PSGallery Version.*|update appveyor.*/
only_commits:
  files:
    - templates/
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: |
    find-module -Repository PSGallery -Name Pester | Out-Null
    Install-Module -Name Pester -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    find-module -Repository PSGallery -Name posh-git | Out-Null
    Install-Module -Name posh-git -Force -Repository PSGallery -SkipPublisherCheck | Out-Null
    $env:Path += ";$env:ProgramFiles\Git\cmd"
    Write-Verbose "Building XML..."
    . .\AppVeyor\AddTemplate.ps1 -verbose
test_script:
  - ps: |
      write-verbose "Running Pester..."
      $pest = Invoke-Pester -passthru -verbose
      if ($pest.FailedCount -gt 0) { 
        throw "$($pest.FailedCount) tests failed."
        }
deploy_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github):x-oauth-basic@github.com`n"
  - git config --global user.email "ryan@ryancbutler.com"
  - git config --global user.name "Ryan Butler"
  - git config --global core.autocrlf false
  - git config --global core.safecrlf false
  - ps: |
      Write-Verbose "Deploying..."
      . .\AppVeyor\Deploying.ps1 -verbose
environment:
  PSGKey:
    secure: XbgpBX+B+lBgfWt4379Ez1823W4nLM2zPlOWWvw8zGrvKmZD7/uIlpLYrW4zpjMb
  github:
    secure: qJwCE47jamnSv6Au8wD9CcJmovghdkcm/qoX0IjWa3SDGaeZkGQlQMUlfW9RlsHe